app/urls.py
from django.contrib import admin
from django.urls import path, include

# app_name='blog'
urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'^tz_detect/', include('tz_detect.urls')),
    path(r'', include('blog.urls')),
]

blog/urls.py
from django.conf.urls import url, include

from . import views

app_name = 'blog'
urlpatterns = [
  # url(r'^$', views.PostListView.as_view(), name='index'),
  url(r'^$', views.index, name='index'),
  url(r'^add/$', views.add, name='add'),
  url(r'^delete/(?P<post_id>[0-9]+)/$', views.delete, name='delete'),
  url(r'^edit/(?P<post_id>[0-9]+)/', views.edit, name='edit'),
]

blog/models.py
from django.db import models

from django.utils import timezone

# Create your models here.
class User(models.Model):
  username = models.CharField(max_length=256, blank=False, null=False)
  password = models.CharField(max_length=256, blank=False, null=False)

  def __str__(self):
    """A human representation of the user object"""
    return "username: {0} | password: {1}".format(self.username, self.password) 

class Post(models.Model):
  created = models.DateTimeField(default=timezone.now())

  modified = models.DateTimeField(default=timezone.now())
  
  title = models.CharField(max_length=256, blank=False, null=False)

  body = models.TextField(blank=False, null=False)

  def __str__(self):
    """A human representation of the post object"""
    return "created: {0} | modifed: {1} | title: {2} | body: {3}".format(self.created, self.modified, self.title, self.body)

  def save(self, *args, **kwargs):
    """ Add created_at and updated_at timestamps. """
    
    self.modified = timezone.now()
    if not self.id:
        self.created = timezone.now()


    return super(Post, self).save(*args, **kwargs)

blog/forms.py
from django import forms

class PostForm (forms.Form):
  
  title = forms.CharField(label='Title', max_length=256, )
  body = forms.CharField(widget=forms.Textarea(attrs={'class':'materialize-textarea'}), label='Post')

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse , HttpResponseRedirect
from django.utils import timezone
from django.forms.models import model_to_dict
from .forms import PostForm
from .models import Post
from django.views.generic import ListView

# Create your views here.

def index(request):

  post_list = Post.objects.all().order_by('id')
  return render(request, 'blog/index.html', {
    'post_list' : post_list
  })

# class PostListView(ListView):
#   model = Post
#   template_name = 'blog/index.html'

#   def get_context_data(self, **kwargs):
#     context = super(PostListView, self).get_context_data(**kwargs)
#     return context

def add(request):

  if request.method == "POST":
    form = PostForm(request.POST)
    
    if form.is_valid():
      Post(
        title=form.cleaned_data["title"],
        body=form.cleaned_data["body"]
      ).save()

      return redirect("blog:index")
    
    else:
      return render(request, 'blog/add.html', {'form' : form})

  else:

    context = { 'header' : 'GET', 'form' : PostForm() }

    return render(request, 'blog/add.html', context)

def edit(request, post_id):
  print(request.method)
  if request.method == "POST":
    form = PostForm(request.POST)
    
    if form.is_valid():
      updatedPost = Post.objects.get(id=post_id)
      updatedPost.title = form.cleaned_data["title"]
      updatedPost.body = form.cleaned_data["body"]
      updatedPost.save()
    
      # Post.objects.filter(id=post_id).update(title=form.cleaned_data["title"], body=form.cleaned_data["body"])
      # print('valid')
      return redirect("blog:index")
    
    else:
      # print('invalid')
      return render(request, 'blog/edit.html', {'form' : form, "id":post_id})

  else:

    updatedPost = Post.objects.get(id=post_id)
    print(updatedPost.title)
    updateForm = PostForm(initial=model_to_dict(updatedPost))
    context = { 'header' : 'GET', 'form' : updateForm, "id":post_id }

    return render(request, 'blog/edit.html', context)

    
def delete(request, post_id):
  if request.method == "DELETE":
    print(request.method)
    print(post_id)
    post = get_object_or_404(Post, id=post_id)
    
    Post.objects.filter(id=post_id).delete()
    return HttpResponse(status=204)

  else:
    return redirect("blog:index")
  
    

  

blog/templates/blog/add.html
{% extends 'blog/base.html' %}
{% load materializecss %}

{% block title %} Blog {% endblock %}

{% block content %}
  <h1>Add a new post</h1>
  <div class="divider"></div>
  <div class="row">
    <form class="col s12" method="post" action="{% url 'blog:add' %}">
      
      {% csrf_token %}
      {{ form|materializecss}}
      
      <button class="btn waves-effect waves-light" type="submit">Save
        <i class="material-icons right">send</i>
      </button>
    </form>
  </div>

{% endblock %}

blog/templates/blog/base.html
<!DOCTYPE html>

<html lang="en">
<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
  
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
  <nav>
    <div class="nav-wrapper">
      <a href="{% url 'blog:index' %}" class="brand-logo">Blog</a>
      <a href="#" data-target="mobile-nav" class="sidenav-trigger"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <li><a href="{% url 'blog:index' %}">Home</a></li>
        <li><a href="{% url 'blog:add' %}">Add Post</a></li>
        <li><a class="edit-btn">Edit Blog</a></li>
      </ul>
    </div>
  </nav>

  <ul class="sidenav" id="mobile-nav">
    <li><a href="{% url 'blog:index' %}">Home</a></li>
    <li><a href="{% url 'blog:add' %}">Add Post</a></li>
    <li><a class="edit-btn">Edit Blog</a></li>
  </ul>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
  
  <script src="{% static 'blog/js/script.js' %}"></script>
</body>
</html>

blog/templates/blog/base_alt.html
<!DOCTYPE html>

<html lang="en">
<head>
  {% load static %}
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
  <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
  
  <title>{% block title %}{% endblock %}</title>
</head>
<body>
  <nav>
    <div class="nav-wrapper indigo darken-3">
      <a href="{% url 'blog:index' %}" class="brand-logo left">Blog</a>
      <a href="#" data-target="mobile-nav" class="right sidenav-trigger hide-on-med-and-up"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-small-and-down">
        <li><a href="{% url 'blog:index' %}">Home</a></li>
      </ul>
    </div>
  </nav>

  <ul class="sidenav" id="mobile-nav">
    <li><a href="{% url 'blog:index' %}">Home</a></li>
  </ul>
  <div class="container">
    {% block content %}
    {% endblock %}
  </div>
  
  <script src="{% static 'blog/js/script.js' %}"></script>
</body>
</html>

blog/templates/blog/edit.html
{% extends 'blog/base.html' %}
{% load materializecss %}

{% block title %} Blog {% endblock %}

{% block content %}
  <h3 class="center-align">Edit Post</h3>
  
  <div class="row blue lighten-5">
    <form class="col s12" method="post" action="">
      
      {% csrf_token %}
      {{ form|materializecss}}
      
      <button class="btn waves-effect waves-light blue darken-1" type="submit">Save
        <i class="material-icons right">send</i>
      </button>
    </form>
  </div>

{% endblock %}

blog/templates/blog/index.html
{% extends 'blog/base.html' %}

{% load tz_detect %}
{% block title %} Blog {% endblock %}

{% block content %}
  <h1 class="center-align">Welcome To My Blog</h1>

  
  {% if post_list %}
  
  {% for post in post_list reversed %} 
  <div class="section blue lighten-5">
    <div class="headline">
      <h4>{{post.title|title}}</h4>
      <div class="right-align">
        <a class="waves-effect waves-light btn icon btn-floating edit-post blue darken-1 scale-transition scale-out" data-id={{post.id}}><i class="material-icons">edit</i></a>
        <a class="waves-effect waves-light btn icon btn-floating delete-post blue darken-1 scale-transition scale-out" data-id={{post.id}}><i class="material-icons">delete</i></a>
      </div>
    </div>
    <div class="divider"></div>
    <pre class="post">{{post.body|linebreaks}}</pre>

    {% ifequal post.created.date post.modified.date %}
      {% ifequal post.created.time post.modified.time %}
      <p class="right-align date">Written: {{post.created}}</p>
      {% tz_detect %}
      {% else %}
      <p class="right-align date">Modified: {{post.modified}}</p>
      {% tz_detect %}
      {% endifequal  %}
    {% else %}
    <p class="right-align date">Modified: {{post.modified}} </p>
    {% tz_detect %}
    {% endifequal  %}
  </div>
  
  {% endfor %}
  
  {% else %}
  <div class="section blue lighten-5 no-post">
    <h5 class="center-align">No blog posts yet.</h5>
  </div>
  {% endif %}


  <div id="confirm-delete-modal" class="modal">
    <div class="modal-content">
      <h4>Do you want to delete post?</h4>
    </div>
    <div class="modal-footer">
      <a class="modal-close waves-effect waves-green btn-flat" id="delete-yes">Yes</a>
      <a class="modal-close waves-effect waves-green btn-flat">No</a>
    </div>
  </div>

{% endblock %}